# Generated by Django 4.2.9 on 2026-07-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rasm_phash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hisobot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targibot_utgan_joy', models.IntegerField(blank=True, null=True)),
                ('qatnashchilar_soni', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Boshlangan'), (1, 'Yuborilgan'), (2, 'Tasdiqlangan'), (3, 'Rad etilgan')], default=0)),
                ('targibot_turi', models.IntegerField(blank=True, choices=[(1, 'Offline'), (2, 'Online')], null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('offline_18_gacha', models.IntegerField(default=0)),
                ('offline_18_katta', models.IntegerField(default=0)),
                ('online_18_gacha', models.IntegerField(default=0)),
                ('online_18_katta', models.IntegerField(default=0)),
                ('proof_url', models.CharField(blank=True, max_length=500, null=True)),
                ('video_kontent_soni', models.IntegerField(default=0)),
                ('banner_soni', models.IntegerField(default=0)),
                ('flayer_soni', models.IntegerField(default=0)),
                ('buklet_soni', models.IntegerField(default=0)),
                ('boshqa_material_soni', models.IntegerField(default=0)),
                ('suhbat_soni', models.IntegerField(default=0)),
                ('qushilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_vaqt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hisobot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Murojaat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('fish', models.CharField(blank=True, max_length=255)),
                ('jinsi', models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('fabula', models.TextField(blank=True)),
                ('zarar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('yosh', models.SmallIntegerField(blank=True, null=True)),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('takroriy', 'Takroriy murojaat'), ('aybi', "Fuqaroning o'z aybi"), ('togri', "To'g'ridan to'g'ri ariza")], default='yangi', max_length=20)),
                ('ijtimoiy_tarmoq', models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('bigolive', 'Bigo Live'), ('boshqa', 'Boshqa')], max_length=20)),
                ('kasb_izoh', models.TextField(blank=True)),
                ('kasb_muassasa', models.CharField(blank=True, max_length=255)),
                ('kasb_kurs', models.SmallIntegerField(blank=True, null=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'murojaat',
                'ordering': ['-sana', '-yaratilgan'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MurojaatKasb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=500)),
                ('daraja', models.IntegerField(default=1)),
                ('tartib', models.IntegerField(default=0)),
                ('is_talaba', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'murojaat_kasb',
                'ordering': ['tartib'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MurojaatUsul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=500)),
                ('daraja', models.IntegerField(default=1)),
                ('tartib', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'murojaat_usul',
                'ordering': ['tartib'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm_url', models.CharField(max_length=500)),
                ('file_unique_id', models.CharField(blank=True, max_length=128, null=True)),
                ('phash', models.CharField(blank=True, max_length=64, null=True)),
                ('qushilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rasm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TargibotUtkazilganJoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targibot_utkazilgan_joy', models.CharField(max_length=255)),
                ('joy_turi', models.IntegerField(default=1)),
                ('kategoriya', models.IntegerField(choices=[(1, 'Mahallalar'), (2, "Oliy ta'lim"), (3, 'Akademik litseylar'), (4, "O'rta ta'lim"), (5, "Maktabgacha ta'lim"), (6, 'Kasalxona'), (7, 'Bozorlar'), (8, 'HMQO'), (9, 'Boshqa'), (10, "Istirohat bog'lari"), (11, 'Jamoat transporti'), (12, 'Masjidar')], default=9)),
            ],
            options={
                'db_table': 'targibot_utkazilgan_joy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman_nomi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tuman',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inspektor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='viloyat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='KunlikIshlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Tayyorlanmoqda'), (2, 'Yuborildi'), (3, 'Tasdiqlandi'), (4, 'Rad etildi')], default=1)),
                ('rad_sababi', models.TextField(blank=True, default='')),
                ('qizil_mfy_soni', models.IntegerField(default=0)),
                ('istirohat_soni', models.IntegerField(default=0)),
                ('transport_soni', models.IntegerField(default=0)),
                ('masjid_soni', models.IntegerField(default=0)),
                ('iio_tv_murojaati', models.IntegerField(default=0)),
                ('uchrashuv_proof_url', models.CharField(blank=True, default='', max_length=500)),
                ('uchrashuv_proof_rasm', models.CharField(blank=True, default='', max_length=500)),
                ('oav_tv_soni', models.IntegerField(default=0)),
                ('oav_tv_url', models.CharField(blank=True, default='', max_length=500)),
                ('oav_radio_soni', models.IntegerField(default=0)),
                ('oav_radio_url', models.CharField(blank=True, default='', max_length=500)),
                ('oav_gazeta_jurnal_soni', models.IntegerField(default=0)),
                ('oav_gazeta_jurnal_url', models.CharField(blank=True, default='', max_length=500)),
                ('oav_video_soni', models.IntegerField(default=0)),
                ('oav_video_10k', models.IntegerField(default=0)),
                ('oav_video_100k', models.IntegerField(default=0)),
                ('oav_video_1m', models.IntegerField(default=0)),
                ('oav_video_url', models.CharField(blank=True, default='', max_length=500)),
                ('oav_internet_soni', models.IntegerField(default=0)),
                ('oav_internet_url', models.CharField(blank=True, default='', max_length=500)),
                ('mat_ijtimoiy_tarmoq', models.IntegerField(default=0)),
                ('mat_oz_tashabbusi', models.IntegerField(default=0)),
                ('mat_flayer_buklet', models.IntegerField(default=0)),
                ('mat_led_ekran', models.IntegerField(default=0)),
                ('mat_boshqa', models.IntegerField(default=0)),
                ('mat_proof_url', models.CharField(blank=True, default='', max_length=500)),
                ('mat_proof_rasm', models.CharField(blank=True, default='', max_length=500)),
                ('suhbat_soni', models.IntegerField(default=0)),
                ('suhbat_proof_url', models.CharField(blank=True, default='', max_length=500)),
                ('suhbat_proof_rasm', models.CharField(blank=True, default='', max_length=500)),
                ('iio_xizmat_soni', models.IntegerField(default=0)),
                ('hamkor_tashkilot_soni', models.IntegerField(default=0)),
                ('sayber_soni', models.IntegerField(default=0)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('viloyat', models.ForeignKey(db_column='viloyat_id', on_delete=django.db.models.deletion.CASCADE, to='core.viloyat')),
            ],
            options={
                'db_table': 'kunlik_ishlar',
                'ordering': ['-sana'],
                'unique_together': {('viloyat', 'sana')},
            },
        ),
    ]
