# Generated by Django 4.2.9 on 2026-07-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hisobot_murojaat_murojaatkasb_murojaatusul_rasm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HamkorTashkilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('turi', models.CharField(blank=True, default='', max_length=100)),
                ('manzil', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('viloyat', models.ForeignKey(db_column='viloyat_id', on_delete=django.db.models.deletion.CASCADE, related_name='hamkor_tashkilotlar', to='core.viloyat')),
            ],
            options={
                'db_table': 'hamkor_tashkilot',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='HamkorXodim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('lavozim', models.CharField(blank=True, default='', max_length=255)),
                ('tel', models.CharField(blank=True, default='', max_length=50)),
                ('tg_id', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('tashkilot', models.ForeignKey(db_column='tashkilot_id', on_delete=django.db.models.deletion.CASCADE, related_name='xodimlar', to='core.hamkortashkilot')),
            ],
            options={
                'db_table': 'hamkor_xodim',
                'ordering': ['fio'],
            },
        ),
    ]
