# Generated by Django 4.2.9 on 2026-07-08 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hamkortashkilot_hamkorxodim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViloyatInfratuzilma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qizil_mfy', models.IntegerField(default=0)),
                ('oliy_talim', models.IntegerField(default=0)),
                ('akademik_litsey', models.IntegerField(default=0)),
                ('orta_talim', models.IntegerField(default=0)),
                ('maktabgacha', models.IntegerField(default=0)),
                ('kasalxona', models.IntegerField(default=0)),
                ('bozor', models.IntegerField(default=0)),
                ('xmko', models.IntegerField(default=0)),
                ('telegram', models.IntegerField(default=0)),
                ('istirohat', models.IntegerField(default=0)),
                ('jamoat_transport', models.IntegerField(default=0)),
                ('masjid', models.IntegerField(default=0)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('viloyat', models.OneToOneField(db_column='viloyat_id', on_delete=django.db.models.deletion.CASCADE, related_name='infratuzilma', to='core.viloyat')),
            ],
            options={
                'db_table': 'viloyat_infratuzilma',
            },
        ),
    ]
