# Generated by Django 4.2.9 on 2026-07-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_viloyat_infratuzilma'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamkorxodim',
            name='mahalla',
            field=models.ForeignKey(blank=True, db_column='mahalla_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hamkor_xodimlar', to='core.mahalla'),
        ),
    ]
