# Generated by Django 4.2.9 on 2026-07-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hamkortashkilot_mahalla_hamkorxodim_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamkortashkilot',
            name='tuman',
            field=models.ForeignKey(blank=True, db_column='tuman_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hamkor_tashkilotlar', to='core.tuman'),
        ),
    ]
