# Generated by Django 5.2.5 on 2026-09-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hamkortashkilot_tuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunlikishlar',
            name='probatsiya_soni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viloyatinfratuzilma',
            name='probatsiya',
            field=models.IntegerField(default=0),
        ),
    ]
