# Generated by Django 5.2.5 on 2026-09-08 17:50

import django.db.models.deletion
from django.db import migrations, models

# Eski ViloyatInfratuzilma maydonlarini TargibotUtkazilganJoy.KATEGORIYA
# kodlariga to'g'ri bog'lash (eski kodda ba'zi maydonlar noto'g'ri kategoriya
# raqamiga bog'langan edi — bu yerda to'g'rilanadi).
FIELD_TO_KATEGORIYA = {
    'qizil_mfy': 1,
    'oliy_talim': 2,
    'kasalxona': 3,
    'bozor': 4,
    'istirohat': 5,
    'jamoat_transport': 6,
    'masjid': 7,
    'xmko': 8,
    'telegram': 9,
    'orta_talim': 14,
    'maktabgacha': 15,
    'akademik_litsey': 16,
    'probatsiya': 11,
}


def copy_infra_data(apps, schema_editor):
    ViloyatInfratuzilma = apps.get_model('core', 'ViloyatInfratuzilma')
    ViloyatJoySoni = apps.get_model('core', 'ViloyatJoySoni')
    rows = []
    for inf in ViloyatInfratuzilma.objects.all():
        for field, kategoriya in FIELD_TO_KATEGORIYA.items():
            soni = getattr(inf, field, 0) or 0
            if soni:
                rows.append(ViloyatJoySoni(viloyat_id=inf.viloyat_id, kategoriya=kategoriya, soni=soni))
    if rows:
        ViloyatJoySoni.objects.bulk_create(rows)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_probatsiya_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViloyatJoySoni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoriya', models.IntegerField(choices=[(1, 'Қизил МФЙлар'), (2, 'Олий таълим муассасалари'), (3, 'Касалхона ва поликлиника'), (4, 'Бозорлар ва йирик савдо мажмуалари'), (5, 'Истироҳат боғлари ва кунгил очар жойлар'), (6, 'Жамоат транспортлари'), (7, 'Масжидлар'), (8, 'ҲМҚО'), (9, 'Бошқа идора ва ташкилотлар'), (10, 'Аҳоли гавжум жойларда'), (11, "Probatsiya ro'yxatidagi shaxslar"), (12, 'Ijtimoiy tarmoqlar (onlayn)'), (14, 'Мактаблар'), (15, 'Мактабгача таълим ташкилотлари'), (16, 'Литсей ва техникумлар')])),
                ('soni', models.IntegerField(default=0)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('viloyat', models.ForeignKey(db_column='viloyat_id', on_delete=django.db.models.deletion.CASCADE, related_name='joy_sonlari', to='core.viloyat')),
            ],
            options={
                'db_table': 'viloyat_joy_soni',
                'unique_together': {('viloyat', 'kategoriya')},
            },
        ),
        migrations.RunPython(copy_infra_data, noop),
    ]
