# Generated by Django 4.2.9 on 2026-09-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_viloyat_joy_soni'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kunlikishlar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kunlikishlar',
            name='tuman',
            field=models.ForeignKey(blank=True, db_column='tuman_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tuman'),
        ),
        migrations.AddField(
            model_name='viloyat',
            name='faqat_shahar_tumani',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='kunlikishlar',
            unique_together={('viloyat', 'tuman', 'sana')},
        ),
    ]
